# Generated by Django 3.2.12 on 2022-02-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pwd',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='文章密码'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, '前端'), (1, '后端'), (2, '其它')], null=True, verbose_name='文章分类'),
        ),
    ]
